// Generated by ReScript, PLEASE EDIT WITH CARE


var screens = [
  {
    place: "Room",
    computer: undefined,
    description: "Вы стоите посреди комнаты.",
    options: [
      [
        "Подойти к столу",
        "Table"
      ],
      [
        "Подойти к окну",
        "Window"
      ],
      [
        "Подойти к двери",
        "Door"
      ]
    ]
  },
  {
    place: "Table",
    computer: undefined,
    description: "Вы стоите у стола.",
    options: [[
        "Вернуться",
        "Room"
      ]]
  },
  {
    place: "Window",
    computer: undefined,
    description: "Вы стоите у окна.",
    options: [[
        "Вернуться",
        "Room"
      ]]
  },
  {
    place: "Door",
    computer: "Door",
    description: "Вы стоите у двери.",
    options: [[
        "Вернуться",
        "Room"
      ]]
  }
];

export {
  screens ,
}
/* No side effect */
