// Generated by ReScript, PLEASE EDIT WITH CARE


var screens = [
  {
    place: "Room",
    computer: undefined,
    description: "Вы стоите посреди комнаты.",
    options: [
      "Подойти к столу",
      "Подойти к окну",
      "Подойти к двери"
    ]
  },
  {
    place: "Table",
    computer: undefined,
    description: "Вы стоите у стола.",
    options: [
      "Подойти к окну",
      "Подойти к двери"
    ]
  },
  {
    place: "Window",
    computer: undefined,
    description: "Вы стоите у окна.",
    options: [
      "Подойти к столу",
      "Подойти к двери"
    ]
  },
  {
    place: "Door",
    computer: "Door",
    description: "Вы стоите у двери.",
    options: [
      "Подойти к столу",
      "Подойти к окну"
    ]
  }
];

export {
  screens ,
}
/* No side effect */
