// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Robot from "../lib/Robot.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as Robot3 from "robot3";
import * as ReactRobot from "react-robot";
import * as JsxRuntime from "react/jsx-runtime";

var Info = {};

var M = Robot.Make(Info);

var machine = Robot3.createMachine("Start", M.states([
          [
            "Start",
            Robot3.state(Robot3.transition("Listen", "Listen"))
          ],
          [
            "Listen",
            Robot3.state(Robot3.transition("GoBack", "Start"), Robot3.transition("ListenToRecording", "ListenToRecording"))
          ],
          [
            "ListenToRecording",
            Robot3.state(Robot3.transition("GoBack", "Start"))
          ]
        ]), (function () {
        return {
                count: 0
              };
      }));

function Game$Start(props) {
  var send = props.send;
  return JsxRuntime.jsx($$Screen.make, {
              content: JsxRuntime.jsx("p", {
                    children: "You were chosen to participate in a secret experiment."
                  }),
              options: [[
                  "Listen",
                  (function () {
                      send("Listen");
                    })
                ]]
            });
}

var Start = {
  make: Game$Start
};

function Game$Listen(props) {
  var send = props.send;
  return JsxRuntime.jsx($$Screen.make, {
              content: JsxRuntime.jsx("p", {
                    children: "You are listening to a recording of a person who is being tortured."
                  }),
              options: [
                [
                  "Listen to the recording",
                  (function () {
                      send("ListenToRecording");
                    })
                ],
                [
                  "Go back",
                  (function () {
                      send("GoBack");
                    })
                ]
              ]
            });
}

var Listen = {
  make: Game$Listen
};

function Game$ListenToRecording(props) {
  var send = props.send;
  return JsxRuntime.jsx($$Screen.make, {
              content: JsxRuntime.jsx("p", {
                    children: "You are hearing strange letters: B Y M N."
                  }),
              options: [[
                  "Go back",
                  (function () {
                      send("GoBack");
                    })
                ]]
            });
}

var ListenToRecording = {
  make: Game$ListenToRecording
};

function Game(props) {
  var match = ReactRobot.useMachine(machine, undefined);
  var send = match[1];
  var state = match[0];
  var match$1 = state.name;
  switch (match$1) {
    case "Start" :
        return JsxRuntime.jsx(Game$Start, {
                    state: state,
                    send: send
                  });
    case "Listen" :
        return JsxRuntime.jsx(Game$Listen, {
                    state: state,
                    send: send
                  });
    case "ListenToRecording" :
        return JsxRuntime.jsx(Game$ListenToRecording, {
                    state: state,
                    send: send
                  });
    
  }
}

var make = Game;

export {
  Info ,
  M ,
  machine ,
  Start ,
  Listen ,
  ListenToRecording ,
  make ,
}
/* M Not a pure module */
