// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Robot from "../lib/Robot.res.mjs";
import * as Robot3 from "robot3";
import * as ReactRobot from "react-robot";
import * as JsxRuntime from "react/jsx-runtime";

var Info = {};

var Machine = Robot.Make(Info);

var machine = Robot3.createMachine("Start", Object.fromEntries([
          [
            "Start",
            Robot3.state(Robot3.transition("Listen", "Listen"))
          ],
          [
            "Listen",
            Robot3.state(Robot3.transition("GoAway", "GoAway"))
          ],
          [
            "GoAway",
            Robot3.state(Robot3.transition("Run", "Run"))
          ],
          [
            "Run",
            Robot3.state(Robot3.transition("Start", "Start"))
          ]
        ]), (function (initialContext) {
        
      }));

function Game$Start(props) {
  var send = props.send;
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsxs("article", {
                      children: [
                        JsxRuntime.jsx("p", {
                              children: "You were chosen to participate in a secret experiment."
                            }),
                        JsxRuntime.jsx("p", {
                              children: "But a recent study shows that to be a lie."
                            })
                      ]
                    }),
                JsxRuntime.jsx("nav", {
                      children: JsxRuntime.jsxs("ul", {
                            children: [
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("a", {
                                          children: "Listen",
                                          href: "#",
                                          onClick: (function (param) {
                                              send("Listen");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("a", {
                                          children: "Go away",
                                          href: "#",
                                          onClick: (function (param) {
                                              send("GoAway");
                                            })
                                        })
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: JsxRuntime.jsx("a", {
                                          children: "Run",
                                          href: "#",
                                          onClick: (function (param) {
                                              send("Run");
                                            })
                                        })
                                  })
                            ]
                          })
                    })
              ]
            });
}

var Start = {
  make: Game$Start
};

function Game(props) {
  var match = ReactRobot.useMachine(machine, undefined);
  return JsxRuntime.jsx(Game$Start, {
              send: match[1]
            });
}

var make = Game;

export {
  Info ,
  Machine ,
  machine ,
  Start ,
  make ,
}
/* Machine Not a pure module */
