// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Terminal from "./terminals/Terminal.res.mjs";
import * as RoomTable from "./rooms/RoomTable.res.mjs";
import * as RoomCenter from "./rooms/RoomCenter.res.mjs";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var NotFound = /* @__PURE__ */Caml_exceptions.create("PathMap.NotFound");

var map = new Map([
      [
        "RoomCenter",
        {
          left: RoomCenter.make,
          right: Terminal.make
        }
      ],
      [
        "RoomTable",
        {
          left: RoomTable.make,
          right: Terminal.make
        }
      ]
    ]);

function get(current) {
  var info = map.get(current);
  if (info !== undefined) {
    return info;
  }
  throw {
        RE_EXN_ID: NotFound,
        _1: current,
        Error: new Error()
      };
}

export {
  NotFound ,
  map ,
  get ,
}
/* map Not a pure module */
