// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "./Store.res.mjs";
import * as Utils from "./Utils.res.mjs";
import * as React from "react";
import * as $$Screen from "./Screen.res.mjs";
import * as HookSwitch from "./HookSwitch.res.mjs";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as MobxReactLite from "mobx-react-lite";
import * as JsxRuntime from "react/jsx-runtime";

var options = [[
    "Вернуться",
    "RoomCenter"
  ]];

var make = MobxReactLite.observer(function (props) {
      var entry = Store.get("RoomTable");
      var state;
      state = entry.TAG === "RoomDoor" ? PervasivesU.failwith("RoomTable state not found") : entry._0;
      var note1 = HookSwitch.Toggle.useSwitch(state.note1);
      React.useEffect((function () {
              Store.update("RoomTable", (function (state) {
                      if (state.TAG === "RoomDoor") {
                        return PervasivesU.failwith("RoomTable state not found");
                      } else {
                        state._0.note1 = note1.state;
                        return ;
                      }
                    }));
            }), [note1.state]);
      var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              Utils.strings([
                    "Вы стоите перед столом.",
                    "На столе разбросаны документы, фотографии и записки."
                  ]),
              note1.link("Читать заметку."),
              note1.content(JsxRuntime.jsx("p", {
                        children: "\"Привет, мир!\""
                      }))
            ]
          });
      return JsxRuntime.jsx($$Screen.make, {
                  content: content,
                  options: options,
                  goTo: props.goTo
                });
    });

make.displayName = "RoomTable";

export {
  options ,
  make ,
}
/* make Not a pure module */
