// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "./Store.res.mjs";
import * as Utils from "./Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as MobxReactLite from "mobx-react-lite";
import * as JsxRuntime from "react/jsx-runtime";

var store = Store.makeStore({
      count: 1,
      options: [[
          "Вернуться",
          "RoomCenter"
        ]]
    });

function addOpenDoorTransition() {
  var exitTransition = [
    "Выйти",
    "RoomTable"
  ];
  store.update(function (state) {
        var existing = state.options.find(function (transition) {
              return Caml_obj.equal(transition, exitTransition);
            });
        if (Core__Option.isNone(existing)) {
          state.options.push(exitTransition);
          return ;
        }
        
      });
}

var make = MobxReactLite.observer(function (props) {
      var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              Utils.strings([
                    "Вы стоите перед дверью.",
                    "На двери находится терминал."
                  ]),
              " ",
              "Количество посещений: ",
              store.state.count.toString()
            ]
          });
      return JsxRuntime.jsx($$Screen.make, {
                  content: content,
                  options: store.state.options,
                  goTo: props.goTo
                });
    });

make.displayName = "RoomDoor";

export {
  store ,
  addOpenDoorTransition ,
  make ,
}
/* store Not a pure module */
