// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "./Store.res.mjs";
import * as Utils from "./Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as MobxReactLite from "mobx-react-lite";
import * as JsxRuntime from "react/jsx-runtime";

function addOpenDoorTransition() {
  var exitTransition = [
    "Выйти",
    "RoomTable"
  ];
  Store.update("RoomDoor", (function (state) {
          if (state.TAG !== "RoomDoor") {
            return PervasivesU.failwith("RoomDoor state not found");
          }
          var state$1 = state._0;
          var existing = state$1.options.find(function (transition) {
                return Caml_obj.equal(transition, exitTransition);
              });
          if (Core__Option.isNone(existing)) {
            state$1.options.push(exitTransition);
            return ;
          }
          
        }));
}

var make = MobxReactLite.observer(function (props) {
      var entry = Store.get("RoomDoor");
      var state;
      state = entry.TAG === "RoomDoor" ? entry._0 : PervasivesU.failwith("RoomDoor state not found");
      var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              Utils.strings([
                    "Вы стоите перед дверью.",
                    "На двери находится терминал."
                  ]),
              " ",
              "Количество посещений: ",
              state.count.toString()
            ]
          });
      return JsxRuntime.jsx($$Screen.make, {
                  content: content,
                  options: state.options,
                  goTo: props.goTo
                });
    });

make.displayName = "RoomDoor";

export {
  addOpenDoorTransition ,
  make ,
}
/* make Not a pure module */
