// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.res.mjs";
import * as React from "react";
import * as $$Screen from "./Screen.res.mjs";
import * as HookSwitch from "./HookSwitch.res.mjs";
import * as MobxReactLite from "mobx-react-lite";
import * as JsxRuntime from "react/jsx-runtime";

var state = {
  note1: "Unvisited"
};

var options = [[
    "Вернуться",
    "RoomCenter"
  ]];

var make = MobxReactLite.observer(function (props) {
      var note1 = HookSwitch.Toggle.useSwitch(state.note1);
      React.useEffect((function () {
              state.note1 = note1.state;
            }), [note1.state]);
      var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              Utils.strings([
                    "Вы стоите перед столом.",
                    "На столе разбросаны документы, фотографии и записки."
                  ]),
              note1.link("Читать заметку."),
              note1.content(JsxRuntime.jsx("p", {
                        children: "\"Привет, мир!\""
                      }))
            ]
          });
      return JsxRuntime.jsx($$Screen.make, {
                  content: content,
                  options: options,
                  goTo: props.goTo
                });
    });

make.displayName = "RoomTable";

export {
  state ,
  options ,
  make ,
}
/* make Not a pure module */
