// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.res.mjs";
import * as React from "react";
import * as $$Screen from "./Screen.res.mjs";
import * as HookSwitch from "./HookSwitch.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var options = [
  {
    element: "Подойти к столу",
    room: "RoomTable"
  },
  {
    element: "Подойти к окну",
    room: "RoomWindow"
  },
  {
    element: "Подойти к двери",
    room: "RoomDoor"
  }
];

var note1Ref = {
  contents: "Unvisited"
};

function make(props) {
  var note1 = HookSwitch.Toggle.useSwitch(note1Ref.contents);
  React.useEffect((function () {
          note1Ref.contents = note1.state;
        }), [note1.state]);
  var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          Utils.strings([
                "Вы стоите посреди комнаты.",
                "На вашей руке - умные часы.",
                "Вы используете их для записи и чтения заметок."
              ]),
          " ",
          note1.link("Читать заметку."),
          note1.content(JsxRuntime.jsx("p", {
                    children: "\"Привет, мир!\""
                  }))
        ]
      });
  return JsxRuntime.jsx($$Screen.make, {
              content: content,
              options: options,
              goTo: props.goTo
            });
}

make.displayName = "RoomCenter";

export {
  options ,
  note1Ref ,
  make ,
}
/*  Not a pure module */
