// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "./Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var options = [
  [
    "Подойти к столу",
    "RoomTable"
  ],
  [
    "Подойти к окну",
    "RoomWindow"
  ],
  [
    "Подойти к двери",
    "RoomDoor"
  ]
];

function make(props) {
  var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          Utils.strings([
                "Вы стоите посреди комнаты.",
                "На вашей руке - умные часы.",
                "Вы используете их для записи и чтения заметок."
              ]),
          " "
        ]
      });
  return JsxRuntime.jsx($$Screen.make, {
              content: content,
              options: options,
              goTo: props.goTo
            });
}

make.displayName = "RoomCenter";

export {
  options ,
  make ,
}
/*  Not a pure module */
