// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "./Store.res.mjs";
import * as Utils from "./Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as MobxReactLite from "mobx-react-lite";
import * as JsxRuntime from "react/jsx-runtime";

var store = Store.makeStore({
      count: 1,
      options: [{
          element: "Вернуться",
          room: "RoomCenter"
        }]
    });

function openDoorTransition() {
  store.update(function (state) {
        if (state.options.find(function (option) {
                return option.room === "RoomTable";
              }) === undefined) {
          state.options.push({
                element: "Выйти",
                room: "RoomTable"
              });
          return ;
        }
        
      });
}

var make = MobxReactLite.observer(function (props) {
      var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
            children: [
              Utils.strings([
                    "Вы стоите перед дверью.",
                    "На двери находится терминал."
                  ]),
              " ",
              "Количество посещений: ",
              store.state.count.toString()
            ]
          });
      return JsxRuntime.jsx($$Screen.make, {
                  content: content,
                  options: store.state.options,
                  goTo: props.goTo
                });
    });

make.displayName = "RoomDoor";

export {
  store ,
  openDoorTransition ,
  make ,
}
/* store Not a pure module */
