// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "./Link.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function $$Screen(props) {
  var goTo = props.goTo;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("article", {
                      children: props.content
                    }),
                JsxRuntime.jsx("nav", {
                      children: JsxRuntime.jsx("ul", {
                            children: props.options.map(function (option, i) {
                                  return JsxRuntime.jsx("li", {
                                              children: JsxRuntime.jsx(Link.make, {
                                                    onClick: (function () {
                                                        goTo(option.room);
                                                      }),
                                                    children: option.element
                                                  }),
                                              className: Core__Option.getOr(option.hidden, false) ? "hidden" : "list-item"
                                            }, i.toString());
                                })
                          })
                    })
              ],
              className: "prosy screen-w py-0"
            });
}

var make = $$Screen;

export {
  make ,
}
/* Link Not a pure module */
