// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Screen$Link(props) {
  var onClick = props.onClick;
  return JsxRuntime.jsx("a", {
              children: props.children,
              href: "#",
              onClick: (function (param) {
                  onClick();
                })
            });
}

var Link = {
  make: Screen$Link
};

function $$Screen(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("article", {
                      children: props.content
                    }),
                JsxRuntime.jsx("nav", {
                      children: JsxRuntime.jsx("ul", {
                            children: Belt_Array.mapWithIndex(props.options, (function (i, param) {
                                    return JsxRuntime.jsx("li", {
                                                children: JsxRuntime.jsx(Screen$Link, {
                                                      onClick: param[1],
                                                      children: param[0]
                                                    })
                                              }, String(i));
                                  }))
                          })
                    })
              ],
              className: "prosy screen-w py-0"
            });
}

var make = $$Screen;

export {
  Link ,
  make ,
}
/* react/jsx-runtime Not a pure module */
