// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mobx from "mobx";

function makeStore(initial) {
  var state = Mobx.observable(initial);
  var update = Mobx.action(function (updater) {
        updater(state);
      });
  return {
          state: state,
          update: update
        };
}

export {
  makeStore ,
}
/* mobx Not a pure module */
