// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mobx from "mobx";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

var store = Mobx.observable(new Map([
          [
            "RoomDoor",
            {
              TAG: "RoomDoor",
              _0: {
                count: 1,
                options: [[
                    "Вернуться",
                    "RoomCenter"
                  ]]
              }
            }
          ],
          [
            "RoomTable",
            {
              TAG: "RoomTable",
              _0: {}
            }
          ]
        ]));

function get(key) {
  var state = store.get(key);
  if (state !== undefined) {
    return state;
  } else {
    return PervasivesU.failwith("Store key not found");
  }
}

function update(key, updater) {
  var state = store.get(key);
  if (state !== undefined) {
    return updater(state);
  } else {
    return PervasivesU.failwith("Store key not found");
  }
}

export {
  store ,
  get ,
  update ,
}
/* store Not a pure module */
