// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mobx from "mobx";

function makeState(initial, key) {
  var value = Mobx.observable(initial);
  var update = Mobx.action(function (updater) {
        updater(value);
      });
  Mobx.autorun(function () {
        console.log(key, Mobx.toJS(value));
      });
  return {
          value: value,
          update: update
        };
}

export {
  makeState ,
}
/* mobx Not a pure module */
