// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TerminalBase from "./TerminalBase.res.mjs";

var header = "Умные часы 3000";

var styleClass = "bg-blue-400";

var knownCommands = [
  "очистить",
  "помощь"
];

function processMessage(param) {
  var display = param.display;
  var text = param.text;
  switch (text) {
    case "очистить" :
        return display.screen("Clear");
    case "помощь" :
        return display.screen({
                    TAG: "Echo",
                    _0: ["Помощь"]
                  });
    default:
      return display.screen({
                  TAG: "Echo",
                  _0: [text]
                });
  }
}

var make = TerminalBase.makeComponent({
      header: header,
      styleClass: styleClass,
      knownCommands: knownCommands,
      processMessage: processMessage
    });

make.displayName = "TerminalHandwatch";

export {
  header ,
  styleClass ,
  knownCommands ,
  processMessage ,
  make ,
}
/* make Not a pure module */
