// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TerminalBase from "./TerminalBase.res.mjs";

var header = "Введите пароль для открытия двери";

var styleClass = "bg-red-400";

function processMessage(param) {
  var display = param.display;
  if (param.text === "1234") {
    return display.screen({
                TAG: "Echo",
                _0: ["Дверь открыта"]
              });
  } else {
    return display.screen({
                TAG: "Echo",
                _0: ["Неверный пароль"]
              });
  }
}

var make = TerminalBase.makeComponent({
      header: header,
      styleClass: styleClass,
      knownCommands: undefined,
      processMessage: processMessage
    });

var RoomDoorTerminal = {
  header: header,
  styleClass: styleClass,
  knownCommands: undefined,
  processMessage: processMessage,
  make: make
};

var header$1 = "Умные часы 3000";

var styleClass$1 = "bg-blue-400";

var knownCommands = [
  "очистить",
  "помощь"
];

function processMessage$1(param) {
  var display = param.display;
  var text = param.text;
  switch (text) {
    case "очистить" :
        return display.screen("Clear");
    case "помощь" :
        return display.screen({
                    TAG: "Echo",
                    _0: ["Помощь"]
                  });
    default:
      return display.screen({
                  TAG: "Echo",
                  _0: [text]
                });
  }
}

var make$1 = TerminalBase.makeComponent({
      header: header$1,
      styleClass: styleClass$1,
      knownCommands: knownCommands,
      processMessage: processMessage$1
    });

var Handwatch = {
  header: header$1,
  styleClass: styleClass$1,
  knownCommands: knownCommands,
  processMessage: processMessage$1,
  make: make$1
};

export {
  RoomDoorTerminal ,
  Handwatch ,
}
/* make Not a pure module */
