// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useLog(msg) {
  React.useEffect((function () {
          console.log(msg);
        }), [msg]);
}

export {
  useLog ,
}
/* react Not a pure module */
