// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useLog(msg) {
  React.useEffect((function () {
          console.log(msg);
        }), [msg]);
}

function strings(strings$1) {
  return strings$1.join(" ");
}

export {
  useLog ,
  strings ,
}
/* react Not a pure module */
