// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function useLog(msg) {
  React.useEffect((function () {
          console.log(msg);
        }), [msg]);
}

function strings(strings$1) {
  return Belt_Array.joinWith(strings$1, " ", (function (x) {
                return x;
              }));
}

export {
  useLog ,
  strings ,
}
/* react Not a pure module */
