// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function normalize(classes) {
  return classes.split(" ");
}

function fromObject(obj) {
  return Belt_Array.reduce(Belt_Array.map(Js_dict.entries(obj), (function (param) {
                    if (param[1]) {
                      return param[0];
                    } else {
                      return "";
                    }
                  })), "", (function (classes, $$class) {
                return classes + " " + $$class;
              }));
}

var Cn = {
  normalize: normalize,
  fromObject: fromObject
};

function make(tag) {
  return {
          TAG: "Jq",
          _0: document.createElement(tag)
        };
}

function string(text) {
  return {
          TAG: "Jq",
          _0: document.createTextNode(text)
        };
}

function fromElement(element) {
  return {
          TAG: "Jq",
          _0: element
        };
}

function toElement(element) {
  return element._0;
}

function append(t, nodes) {
  var element = t._0;
  Belt_Array.forEach(nodes, (function (node) {
          element.appendChild(node._0);
        }));
  return t;
}

function appendTo(t, node) {
  node.appendChild(t._0);
  return t;
}

function replaceWith(t, node) {
  var element = t._0;
  element.parentNode.replaceChild(element, node);
  return t;
}

function remove(t) {
  var element = t._0;
  element.parentNode.removeChild(element);
  return t;
}

function text(t, text$1) {
  t._0.textContent = text$1;
  return t;
}

function addClass(t, classes) {
  var classes$1 = classes.split(" ");
  Caml_splice_call.spliceObjApply(t._0.classList, "add", [classes$1]);
  return t;
}

function removeClass(t, classes) {
  var classes$1 = classes.split(" ");
  Caml_splice_call.spliceObjApply(t._0.classList, "remove", [classes$1]);
  return t;
}

function toggleClass(t, classes, value) {
  var element = t._0;
  var classes$1 = classes.split(" ");
  Belt_Array.forEach(classes$1, (function ($$class) {
          element.classList.toggle($$class, value);
        }));
  return t;
}

function toggleClasses(t, classes) {
  var entries = Js_dict.entries(classes);
  Belt_Array.forEach(entries, (function (param) {
          toggleClass(t, param[0], param[1]);
        }));
  return t;
}

export {
  Cn ,
  make ,
  string ,
  fromElement ,
  toElement ,
  append ,
  appendTo ,
  replaceWith ,
  remove ,
  text ,
  addClass ,
  removeClass ,
  toggleClass ,
  toggleClasses ,
}
/* No side effect */
