// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function normalize(classes) {
  return classes.split(" ");
}

function fromObject(obj) {
  return Belt_Array.reduce(Belt_Array.map(Js_dict.entries(obj), (function (param) {
                    if (param[1]) {
                      return param[0];
                    } else {
                      return "";
                    }
                  })), "", (function (classes, $$class) {
                return classes + " " + $$class;
              }));
}

var Cn = {
  normalize: normalize,
  fromObject: fromObject
};

function make(tag) {
  return document.createElement(tag);
}

function string(text) {
  return document.createTextNode(text);
}

function fromNode(node) {
  return node;
}

function toNode(t) {
  return t;
}

function append(t, nodes) {
  Belt_Array.forEach(nodes, (function (other) {
          t.appendChild(other);
        }));
  return t;
}

function appendTo(t, other) {
  other.appendChild(t);
  return t;
}

function replaceWith(t, other) {
  t.parentNode.replaceChild(other, t);
  return t;
}

function remove(t) {
  t.parentNode.removeChild(t);
  return t;
}

function setText(t, text) {
  t.textContent = text;
  return t;
}

function getText(t) {
  return t.textContent;
}

function addClass(t, classes) {
  var classes$1 = classes.split(" ");
  Caml_splice_call.spliceObjApply(t.classList, "add", [classes$1]);
  return t;
}

function removeClass(t, classes) {
  var classes$1 = classes.split(" ");
  Caml_splice_call.spliceObjApply(t.classList, "remove", [classes$1]);
  return t;
}

function toggleClass(t, classes, value) {
  var classes$1 = classes.split(" ");
  Belt_Array.forEach(classes$1, (function ($$class) {
          t.classList.toggle($$class, value);
        }));
  return t;
}

function toggleClasses(t, classes) {
  var entries = Js_dict.entries(classes);
  Belt_Array.forEach(entries, (function (param) {
          toggleClass(t, param[0], param[1]);
        }));
  return t;
}

function show(t) {
  var style = t.style;
  style.display = "initial";
  return t;
}

function hide(t) {
  var style = t.style;
  style.display = "none";
  return t;
}

function space() {
  return document.createTextNode(" ");
}

function newline() {
  return document.createElement("br");
}

var Dom = {
  space: space,
  newline: newline
};

export {
  Cn ,
  make ,
  string ,
  fromNode ,
  toNode ,
  append ,
  appendTo ,
  replaceWith ,
  remove ,
  setText ,
  getText ,
  addClass ,
  removeClass ,
  toggleClass ,
  toggleClasses ,
  show ,
  hide ,
  Dom ,
}
/* No side effect */
