// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Node = {};

var Style = {};

var ClassList = {};

var $$Document = {};

export {
  $$Node ,
  Style ,
  ClassList ,
  $$Document ,
}
/* No side effect */
