// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

var $$Node = {};

function add(classList, classes) {
  Caml_splice_call.spliceObjApply(classList, "add", [classes.split(" ")]);
}

function remove(classList, classes) {
  Caml_splice_call.spliceObjApply(classList, "remove", [classes.split(" ")]);
}

function toggle(classList, classes, value) {
  Belt_Array.forEach(classes.split(" "), (function ($$class) {
          classList.toggle($$class, value);
        }));
}

var ClassList = {
  add: add,
  remove: remove,
  toggle: toggle
};

var $$Document = {};

export {
  $$Node ,
  ClassList ,
  $$Document ,
}
/* No side effect */
