// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RoomTable from "./RoomTable.res.mjs";
import * as RoomCenter from "./RoomCenter.res.mjs";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var map = new Map([
      [
        "Center",
        RoomCenter.make
      ],
      [
        "Table",
        RoomTable.make
      ]
    ]);

var NotFound = /* @__PURE__ */Caml_exceptions.create("PathMap.NotFound");

function get(current) {
  var make = map.get(current);
  if (make !== undefined) {
    return make;
  }
  throw {
        RE_EXN_ID: NotFound,
        Error: new Error()
      };
}

export {
  map ,
  NotFound ,
  get ,
}
/* map Not a pure module */
