// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Terminal from "../terminals/Terminal.res.mjs";
import * as RoomTable from "./RoomTable.res.mjs";
import * as RoomCenter from "./RoomCenter.res.mjs";
import * as Caml_exceptions from "rescript/lib/es6/caml_exceptions.js";

var map = new Map([
      [
        "Center",
        [
          RoomCenter.make,
          Terminal.make
        ]
      ],
      [
        "Table",
        [
          RoomTable.make,
          Terminal.make
        ]
      ]
    ]);

var NotFound = /* @__PURE__ */Caml_exceptions.create("PathMap.NotFound");

function get(current) {
  var make = map.get(current);
  if (make !== undefined) {
    return make;
  }
  throw {
        RE_EXN_ID: NotFound,
        Error: new Error()
      };
}

export {
  map ,
  NotFound ,
  get ,
}
/* map Not a pure module */
