// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

var meta_options = [[
    "Вернуться",
    "Center"
  ]];

var meta = {
  room: "Table",
  computer: "Watch",
  options: meta_options
};

function make(props) {
  var content = JsxRuntime.jsx(JsxRuntime.Fragment, {
        children: Caml_option.some(Utils.strings([
                  "Вы стоите перед столом.",
                  "На столе разбросаны документы, фотографии и записки."
                ]))
      });
  return JsxRuntime.jsx($$Screen.make, {
              content: content,
              options: meta_options,
              goTo: props.goTo
            });
}

export {
  meta ,
  make ,
}
/* Utils Not a pure module */
