// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as Switch from "../hooks/Switch.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var meta_options = [
  [
    "Подойти к столу",
    "Table"
  ],
  [
    "Подойти к окну",
    "Window"
  ],
  [
    "Подойти к двери",
    "Door"
  ]
];

var meta = {
  room: "Center",
  computer: "Watch",
  options: meta_options
};

function RoomCenter(props) {
  var note1 = Switch.Toggle.useSwitch(undefined);
  var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          Utils.strings([
                "Вы стоите посреди комнаты.",
                "На вашей руке - умные часы.",
                "Вы используете их для записи и чтения заметок."
              ]),
          " ",
          note1.link("Читать заметку."),
          note1.content(JsxRuntime.jsx("p", {
                    children: "\"Привет, мир!\""
                  }))
        ]
      });
  return JsxRuntime.jsx($$Screen.make, {
              content: content,
              options: meta_options,
              goTo: props.goTo
            });
}

var make = RoomCenter;

export {
  meta ,
  make ,
}
/* Utils Not a pure module */
