// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as Switch from "../hooks/Switch.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

var paths = [
  [
    "Подойти к столу",
    "Table"
  ],
  [
    "Подойти к окну",
    "Window"
  ],
  [
    "Подойти к двери",
    "Door"
  ]
];

var space = " ";

function RoomCenter(props) {
  var goTo = props.goTo;
  var note1 = Switch.Toggle.useSwitch(undefined);
  var options = Belt_Array.map(paths, (function (param) {
          var place = param[1];
          return [
                  param[0],
                  (function () {
                      goTo(place);
                    })
                ];
        }));
  var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          Utils.strings([
                "Вы стоите посреди комнаты.",
                "На вашей руке - умные часы.",
                "Вы используете их для записи и чтения заметок."
              ]),
          space,
          note1.link("Читать заметку."),
          note1.content(JsxRuntime.jsx("p", {
                    children: "\"Привет, мир!\""
                  }))
        ]
      });
  return JsxRuntime.jsx($$Screen.make, {
              content: content,
              options: options
            });
}

var computer = "Watch";

var make = RoomCenter;

export {
  computer ,
  paths ,
  space ,
  make ,
}
/* Utils Not a pure module */
