// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.res.mjs";
import * as React from "react";
import * as $$Screen from "./Screen.res.mjs";
import * as Switch from "../hooks/Switch.res.mjs";
import * as PathMap from "./PathMap.res.mjs";
import * as Terminal from "../terminals/Terminal.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

var options = [
  [
    "Подойти к столу",
    "Table"
  ],
  [
    "Подойти к окну",
    "Window"
  ],
  [
    "Подойти к двери",
    "Door"
  ]
];

var note1Ref = {
  contents: "Unvisited"
};

function make(props) {
  var note1 = Switch.Toggle.useSwitch(note1Ref.contents);
  React.useEffect((function () {
          note1Ref.contents = note1.state;
        }), [note1.state]);
  var content = JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          Utils.strings([
                "Вы стоите посреди комнаты.",
                "На вашей руке - умные часы.",
                "Вы используете их для записи и чтения заметок."
              ]),
          " ",
          note1.link("Читать заметку."),
          note1.content(JsxRuntime.jsx("p", {
                    children: "\"Привет, мир!\""
                  }))
        ]
      });
  return JsxRuntime.jsx($$Screen.make, {
              content: content,
              options: options,
              goTo: props.goTo
            });
}

PathMap.set({
      room: "Center",
      path: make,
      terminal: Terminal.make
    });

export {
  options ,
  note1Ref ,
  make ,
}
/*  Not a pure module */
