// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.res.mjs";
import * as $$Screen from "./Screen.res.mjs";
import * as PathMap from "./PathMap.res.mjs";
import * as Terminal from "../terminals/Terminal.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

var options = [[
    "Вернуться",
    "Center"
  ]];

function make(props) {
  var content = JsxRuntime.jsx(JsxRuntime.Fragment, {
        children: Caml_option.some(Utils.strings([
                  "Вы стоите перед столом.",
                  "На столе разбросаны документы, фотографии и записки."
                ]))
      });
  return JsxRuntime.jsx($$Screen.make, {
              content: content,
              options: options,
              goTo: props.goTo
            });
}

PathMap.set({
      room: "Table",
      make: make,
      terminal: Terminal.make
    });

export {
  options ,
  make ,
}
/*  Not a pure module */
