// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "./Link.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function $$Screen(props) {
  var goTo = props.goTo;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("article", {
                      children: props.content
                    }),
                JsxRuntime.jsx("nav", {
                      children: JsxRuntime.jsx("ul", {
                            children: Belt_Array.mapWithIndex(props.options, (function (i, param) {
                                    var room = param[1];
                                    return JsxRuntime.jsx("li", {
                                                children: JsxRuntime.jsx(Link.make, {
                                                      onClick: (function () {
                                                          goTo(room);
                                                        }),
                                                      children: param[0]
                                                    })
                                              }, String(i));
                                  }))
                          })
                    })
              ],
              className: "prosy screen-w py-0"
            });
}

var make = $$Screen;

export {
  make ,
}
/* Link Not a pure module */
