// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";
import * as $$Screen from "../screen/Screen.res.mjs";
import * as Terminal from "../screen/Terminal.res.mjs";

function render() {
  return Jq.tree("div", [
              $$Screen.Room.render(),
              Terminal.render()
            ], undefined, "flex gap-4 justify-center", undefined, undefined, undefined);
}

export {
  render ,
}
/* Jq Not a pure module */
