// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useDisplay(options) {
  var match = React.useState(function () {
        return [];
      });
  var setOutput = match[1];
  var output = match[0];
  var match$1 = React.useState(function () {
        return 1;
      });
  var setVerticalOffset = match$1[1];
  var verticalOffset = match$1[0];
  var lines = React.useMemo((function () {
          var start = (output.length - options.height | 0) - verticalOffset | 0;
          var start$1 = start > 0 ? start : 0;
          return output.slice(start$1, start$1 + options.height | 0);
        }), [
        output,
        options.height,
        verticalOffset
      ]);
  var viewport = function (direction) {
    switch (direction) {
      case "Up" :
          var start = output.length - options.height | 0;
          var limit = Math.max(0, start);
          return setVerticalOffset(function (prev) {
                      return Math.min(prev + 1 | 0, limit);
                    });
      case "Down" :
          return setVerticalOffset(function (prev) {
                      return Math.max(prev - 1 | 0, 0);
                    });
      case "Reset" :
          return setVerticalOffset(function (param) {
                      return 0;
                    });
      
    }
  };
  var screen = function (command) {
    if (typeof command !== "object") {
      return setOutput(function (param) {
                  return [];
                });
    }
    var newLines = command._0;
    setOutput(function (lines) {
          return lines.concat(newLines);
        });
  };
  return {
          lines: lines,
          screen: screen,
          viewport: viewport
        };
}

export {
  useDisplay ,
}
/* react Not a pure module */
