// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useTick(ms) {
  var match = React.useState(function () {
        return true;
      });
  var setTick = match[1];
  React.useEffect((function () {
          var intervalId = setInterval((function () {
                  setTick(function (prev) {
                        return !prev;
                      });
                }), ms);
          return (function () {
                    clearInterval(intervalId);
                  });
        }), [
        ms,
        setTick
      ]);
  return match[0];
}

function useInput(options) {
  var tick = useTick(400);
  var match = React.useState(function () {
        return false;
      });
  var setFocused = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setMessage = match$1[1];
  var message = match$1[0];
  var beam = tick && match[0] ? "█" : "";
  var focus = function (state) {
    if (state === "On") {
      return setFocused(function (param) {
                  return true;
                });
    } else {
      return setFocused(function (param) {
                  return false;
                });
    }
  };
  var run = function (command) {
    if (typeof command !== "object") {
      if (command === "Clear") {
        return setMessage(function (param) {
                    return "";
                  });
      }
      var allButLast = message.slice(0, message.length - 1 | 0);
      return setMessage(function (param) {
                  return allButLast;
                });
    } else {
      var newMessage = message + command._0;
      var isAllWidth = newMessage.length === (options.width + 1 | 0);
      return setMessage(function (param) {
                  if (isAllWidth) {
                    return message;
                  } else {
                    return newMessage;
                  }
                });
    }
  };
  return {
          message: message,
          beam: beam,
          run: run,
          focus: focus
        };
}

export {
  useTick ,
  useInput ,
}
/* react Not a pure module */
