// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "./Input.res.mjs";
import * as Display from "./Display.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function make(props) {
  var match = Display.useDisplay({
        width: 36,
        height: 13
      });
  var viewport = match.viewport;
  var screen = match.screen;
  var match$1 = Input.useInput({
        width: 36
      });
  var focus = match$1.focus;
  var input = match$1.input;
  var message = match$1.message;
  var processMessage = function (text) {
    var message = text.trim();
    if (message === "очистить") {
      return screen("Clear");
    } else if (message.length > 0) {
      return screen({
                  TAG: "Echo",
                  _0: message
                });
    } else {
      return ;
    }
  };
  var onKeyDown = function (e) {
    var key = e.key;
    switch (key) {
      case "ArrowDown" :
          return viewport("Down");
      case "ArrowUp" :
          return viewport("Up");
      case "Backspace" :
          return input("RemoveChar");
      case "Enter" :
          processMessage(message);
          viewport("Reset");
          return input("Clear");
      default:
        if (key.length === 1) {
          return input({
                      TAG: "AddChar",
                      _0: key
                    });
        } else {
          return ;
        }
    }
  };
  var lines = match.display.map(function (line, i) {
        return JsxRuntime.jsx("div", {
                    children: line
                  }, i.toString());
      });
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Умные часы 3000",
                      className: "text-center"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: lines,
                              className: "flex flex-col grow"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                "> ",
                                JsxRuntime.jsx("span", {
                                      children: message
                                    }),
                                match$1.beam
                              ]
                            })
                      ],
                      className: "flex flex-col"
                    })
              ],
              className: "monospace screen-w screen-h bg-blue-400 outline-0 whitespace-pre text-nowrap  text-gray-800 p-2 flex flex-col justify-between",
              tabIndex: 0,
              onKeyDown: onKeyDown,
              onFocus: (function (param) {
                  focus("On");
                }),
              onBlur: (function (param) {
                  focus("Off");
                }),
              onClick: (function (param) {
                  focus("On");
                })
            });
}

export {
  make ,
}
/* Input Not a pure module */
