// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "./Input.res.mjs";
import * as React from "react";
import * as Display from "./Display.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function make(props) {
  var display = Display.useDisplay({
        width: 36,
        height: 13
      });
  var input = Input.useInput({
        width: 36
      });
  var match = React.useState(function () {
        return false;
      });
  var setHighlighted = match[1];
  var lines = display.lines.map(function (line, i) {
        return JsxRuntime.jsx("div", {
                    children: line
                  }, i.toString());
      });
  var knownCommands = [
    "очистить",
    "помощь"
  ];
  var processMessage = function (text) {
    var message = text.trim();
    switch (message) {
      case "очистить" :
          return display.screen("Clear");
      case "помощь" :
          return display.screen({
                      TAG: "Echo",
                      _0: ["Помощь"]
                    });
      default:
        if (message.length > 0) {
          return display.screen({
                      TAG: "Echo",
                      _0: [message]
                    });
        } else {
          return ;
        }
    }
  };
  var onKeyDown = function (e) {
    var key = e.key;
    if (key.length === 1 || key === "Backspace") {
      var newMessage = input.message + key;
      setHighlighted(function (param) {
            return knownCommands.includes(newMessage);
          });
    }
    switch (key) {
      case "ArrowDown" :
          return display.viewport("Down");
      case "ArrowUp" :
          return display.viewport("Up");
      case "Backspace" :
          return input.run("RemoveChar");
      case "Enter" :
          processMessage(input.message);
          display.viewport("Reset");
          return input.run("Clear");
      default:
        if (key.length === 1) {
          return input.run({
                      TAG: "AddChar",
                      _0: key
                    });
        } else {
          return ;
        }
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "Умные часы 3000",
                      className: "text-center"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: lines,
                              className: "flex flex-col grow"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                "> ",
                                JsxRuntime.jsx("span", {
                                      children: input.message,
                                      className: match[0] ? "bg-green-800 text-white" : ""
                                    }),
                                input.beam
                              ],
                              className: "select-none"
                            })
                      ],
                      className: "flex flex-col"
                    })
              ],
              className: "\n      monospace screen-w screen-h\n      outline-0 whitespace-pre text-nowrap\n      p-2 flex flex-col justify-between\n      text-gray-800 bg-blue-400\n    ",
              tabIndex: 0,
              onKeyDown: onKeyDown,
              onFocus: (function (param) {
                  input.focus("On");
                }),
              onBlur: (function (param) {
                  input.focus("Off");
                }),
              onClick: (function (param) {
                  input.focus("On");
                })
            });
}

export {
  make ,
}
/* Input Not a pure module */
