// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";

function render(child) {
  return Jq.tree("a", [child], undefined, "not-prose text-blue-300 hover:text-blue-400 visited:text-base", undefined, undefined, [[
                "href",
                "#"
              ]]);
}

export {
  render ,
}
/* Jq Not a pure module */
