// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jqx from "../lib/Jqx.res.mjs";

function Link(props) {
  return Jqx.Elements.jsx("a", {
              bind: props.bind,
              class: "not-prose text-blue-300 hover:text-blue-400 visited:text-base",
              attributes: [[
                  "href",
                  "#"
                ]],
              children: Jqx.Elements.someElement(props.children),
              onClickOnce: props.onClickOnce
            });
}

var make = Link;

export {
  make ,
}
/* Jqx Not a pure module */
