// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";
import * as Jqx from "../lib/Jqx.res.mjs";
import * as Switch from "./Switch.res.mjs";

function Screen$Room(props) {
  var note1 = Switch.Toggle.make(undefined);
  var dependencies = [note1.setup];
  return Jqx.Elements.jsxs("div", {
              class: "prosy screen-w py-0",
              dependencies: dependencies,
              children: [
                Jqx.text([
                      "Вы стоите посреди комнаты. На вашей руке - умные часы.",
                      "Вы используете их для записи и чтения заметок."
                    ]),
                Jq.Dom.space(),
                note1.link("Читать заметку."),
                Jq.Dom.newline(),
                note1.content(Jqx.Elements.jsx("span", {
                          children: Jqx.Elements.someElement(Jqx.string("\"Привет, мир!\""))
                        }))
              ]
            });
}

var Room = {
  make: Screen$Room
};

export {
  Room ,
}
/* Jq Not a pure module */
