// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";
import * as Switch from "./Switch.res.mjs";

function render() {
  var link = Jq.tree("span", [Jq.string("Читать заметку.")], undefined, undefined, undefined);
  var content = Jq.tree("span", [Jq.string("\"Привет, мир!\"")], undefined, undefined, undefined);
  Switch.Toggle.make(link, content, undefined);
  return Jq.tree("div", [
              Jq.strings([
                    "Вы стоите посреди комнаты. На вашей руке - умные часы.",
                    "Вы используете их для записи и чтения заметок."
                  ]),
              Jq.Dom.space(),
              link,
              Jq.Dom.newline(),
              content
            ], undefined, undefined, undefined);
}

var Room = {
  render: render
};

export {
  Room ,
}
/* No side effect */
