// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";
import * as Switch from "./Switch.res.mjs";

var link = Jq.tree("span", [Jq.string("Читать заметку.")], undefined, undefined);

var content = Jq.tree("span", [Jq.string("\"Привет, мир!\"")], undefined, undefined);

var note = Switch.Toggle.useSwitch(link, content, undefined);

var Note1 = {
  link: link,
  content: content,
  note: note
};

function render() {
  return Jq.tree("div", [
              Jq.strings([
                    "Вы стоите посреди комнаты. На вашей руке - умные часы.",
                    "Вы используете их для записи и чтения заметок."
                  ]),
              Jq.Dom.space(),
              link,
              Jq.Dom.newline(),
              content
            ], undefined, undefined);
}

var Room = {
  Note1: Note1,
  render: render
};

export {
  Room ,
}
/* link Not a pure module */
