// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";

function replaceWithText(link) {
  var text = Jq.getText(link);
  Jq.replaceWith(link, Jq.string(text));
}

function useSwitch(link, content, initialOpt) {
  var initial = initialOpt !== undefined ? initialOpt : "Unvisited";
  var state = {
    contents: initial
  };
  var update = function (newState) {
    state.contents = newState;
    if (newState !== "Visited") {
      return Jq.hide(content);
    }
    replaceWithText(link);
    Jq.show(content);
  };
  update(initial);
  return {
          toggle: update
        };
}

var Toggle = {
  replaceWithText: replaceWithText,
  useSwitch: useSwitch
};

export {
  Toggle ,
}
/* No side effect */
