// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";

function make(content, initialOpt) {
  var initial = initialOpt !== undefined ? initialOpt : "Unvisited";
  var state = {
    contents: initial
  };
  var update = function (newState) {
    state.contents = newState;
    if (newState === "Visited") {
      return Jq.show(content);
    } else {
      return Jq.hide(content);
    }
  };
  update(initial);
  return {
          toggle: update
        };
}

var Base = {
  make: make
};

function replaceWithText(link) {
  var text = Jq.getText(link);
  Jq.replaceWith(link, Jq.string(text));
}

function make$1(link, content, initialOpt) {
  var initial = initialOpt !== undefined ? initialOpt : "Unvisited";
  var state = {
    contents: initial
  };
  var update = function (newState) {
    state.contents = newState;
    if (newState === "Visited") {
      replaceWithText(link);
      return Jq.show(content);
    }
    Jq.hide(content);
    Jq.onClick(link, (function (param) {
            update("Visited");
          }), {
          once: true
        });
  };
  update(initial);
  return {
          toggle: update
        };
}

var Toggle = {
  replaceWithText: replaceWithText,
  make: make$1
};

export {
  Base ,
  Toggle ,
}
/* No side effect */
