// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jqx from "../lib/Jqx.res.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";

function Terminal(props) {
  return Jqx.Elements.jsx("div", {
              class: "monospace screen-w screen-h outline-0 whitespace-pre text-nowrap text-gray-800 p-2 flex flex-col justify-between",
              classes: Js_dict.fromArray([[
                      "bg-blue-400",
                      true
                    ]]),
              children: Jqx.string("Компьютер")
            });
}

var make = Terminal;

export {
  make ,
}
/* Jqx Not a pure module */
