// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "../lib/Jq.res.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";

function render() {
  return Jq.tree("div", [Jq.strings(["Компьютер"])], undefined, "monospace screen-w screen-h outline-0 whitespace-pre text-nowrap text-gray-800 p-2 flex flex-col justify-between", Js_dict.fromArray([[
                    "bg-blue-400",
                    true
                  ]]), undefined);
}

export {
  render ,
}
/* Jq Not a pure module */
