// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Screen from "./screen/Screen.res.mjs";
import * as Terminal from "./screen/Terminal.res.mjs";
import * as JqxAdapter from "./lib/JqxAdapter.res.mjs";

function Game(props) {
  return JqxAdapter.Elements.jsx("div", {
              class: "w-full h-full min-h-screen m-0 p-6 bg-gray-900 text-gray-100",
              children: JqxAdapter.Elements.someElement(JqxAdapter.Elements.jsx("div", {
                        class: "mx-auto min-w-xl max-w-5xl",
                        children: JqxAdapter.Elements.someElement(JqxAdapter.Elements.jsxs("div", {
                                  class: "flex gap-4 justify-center",
                                  children: JqxAdapter.array([
                                        JqxAdapter.jsx($$Screen.Room.make, {}),
                                        JqxAdapter.jsx(Terminal.make, {})
                                      ])
                                }))
                      }))
            });
}

var make = Game;

export {
  make ,
}
/* Screen Not a pure module */
