// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jqx from "./lib/Jqx.res.mjs";
import * as $$Screen from "./screen/Screen.res.mjs";
import * as Terminal from "./screen/Terminal.res.mjs";

function Game(props) {
  return Jqx.Elements.jsxs("div", {
              class: "flex gap-4 justify-center",
              children: Jqx.array([
                    Jqx.jsx($$Screen.Room.make, {}),
                    Jqx.jsx(Terminal.make, {})
                  ])
            });
}

var make = Game;

export {
  make ,
}
/* Jqx Not a pure module */
