// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "./lib/Jq.res.mjs";
import * as Jqx from "./lib/Jqx.res.mjs";
import * as Game from "./game/Game.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Error from "@rescript/core/src/Core__Error.res.mjs";

function mount(root, children) {
  var root$1 = Jq.fromNode(root);
  Jq.append(root$1, [children]);
}

function render(child) {
  var ref = {
    contents: Jq.Dom.placeholder
  };
  Jqx.Elements.jsx("div", {
        ref: ref,
        class: "w-full h-full min-h-screen m-0 p-6 bg-gray-900 text-gray-100",
        children: Jqx.Elements.jsx("div", {
              class: "mx-auto min-w-xl max-w-5xl",
              children: {
                TAG: "One",
                _0: child
              }
            })
      });
  return ref.contents;
}

var App = {
  mount: mount,
  render: render
};

var rootElement = document.querySelector("#root");

if (rootElement !== undefined) {
  mount(Caml_option.valFromOption(rootElement), render(Game.render()));
} else {
  Core__Error.panic("No root element found!");
}

export {
  App ,
}
/* rootElement Not a pure module */
