// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jqx from "./lib/Jqx.res.mjs";

var x1 = Jqx.Elements.jsx("div", {});

var x2 = Jqx.Elements.jsx("div", {
      class: "test",
      children: Jqx.Elements.jsx("div", {})
    });

var x3 = Jqx.Elements.jsxs("div", {
      children: Jqx.array([
            Jqx.Elements.jsx("div", {}),
            Jqx.Elements.jsx("div", {})
          ])
    });

function Test$Link(props) {
  return Jqx.Elements.jsx("div", {});
}

var Link = {
  make: Test$Link
};

function Test$Nest(props) {
  return Jqx.Elements.jsx("div", {
              children: props.children
            });
}

var Nest = {
  make: Test$Nest
};

var x4 = Jqx.jsx(Test$Link, {
      count: 10
    });

var x5 = Jqx.jsx(Test$Nest, {
      children: Jqx.jsx(Test$Link, {
            count: 10
          })
    });

var x6 = Jqx.jsxs(Test$Nest, {
      children: Jqx.array([
            Jqx.jsx(Test$Link, {
                  count: 10
                }),
            Jqx.jsx(Test$Link, {
                  count: 20
                })
          ])
    });

export {
  x1 ,
  x2 ,
  x3 ,
  Link ,
  Nest ,
  x4 ,
  x5 ,
  x6 ,
}
/* x1 Not a pure module */
