// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JqxAdapter from "./lib/JqxAdapter.res.mjs";

var x1 = JqxAdapter.Elements.jsx("div", {});

var x2 = JqxAdapter.Elements.jsx("div", {
      class: "test",
      children: JqxAdapter.Elements.someElement(JqxAdapter.Elements.jsx("div", {}))
    });

var x3 = JqxAdapter.Elements.jsxs("div", {
      children: JqxAdapter.array([
            JqxAdapter.Elements.jsx("div", {}),
            JqxAdapter.Elements.jsx("div", {})
          ])
    });

function Test$Link(props) {
  return JqxAdapter.Elements.jsx("div", {});
}

var Link = {
  make: Test$Link
};

function Test$Nest(props) {
  return JqxAdapter.Elements.jsx("div", {
              children: JqxAdapter.Elements.someElement(props.children)
            });
}

var Nest = {
  make: Test$Nest
};

var x4 = JqxAdapter.jsx(Test$Link, {
      count: 10
    });

var x5 = JqxAdapter.jsx(Test$Nest, {
      children: JqxAdapter.jsx(Test$Link, {
            count: 10
          })
    });

var x6 = JqxAdapter.jsxs(Test$Nest, {
      children: JqxAdapter.array([
            JqxAdapter.jsx(Test$Link, {
                  count: 10
                }),
            JqxAdapter.jsx(Test$Link, {
                  count: 20
                })
          ])
    });

var x7 = JqxAdapter.jsx(Test$Nest, {
      children: JqxAdapter.jsxs(JqxAdapter.jsxFragment, {
            children: JqxAdapter.array([
                  JqxAdapter.jsx(Test$Link, {
                        count: 10
                      }),
                  JqxAdapter.jsx(Test$Link, {
                        count: 20
                      })
                ])
          })
    });

var x8 = JqxAdapter.jsx(Test$Nest, {
      children: JqxAdapter.jsx(JqxAdapter.jsxFragment, {})
    });

export {
  x1 ,
  x2 ,
  x3 ,
  Link ,
  Nest ,
  x4 ,
  x5 ,
  x6 ,
  x7 ,
  x8 ,
}
/* x1 Not a pure module */
