// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jqx from "./lib/Jqx.res.mjs";

var x = Jqx.Elements.jsx("div", {
      class: "test",
      children: Jqx.Elements.jsx("div", {})
    });

export {
  x ,
}
/* x Not a pure module */
