// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function useDisplay(options) {
  var match = React.useState(function () {
        return [];
      });
  var setLines = match[1];
  var lines = match[0];
  var match$1 = React.useState(function () {
        return 0;
      });
  var setVerticalOffset = match$1[1];
  var verticalOffset = match$1[0];
  var display = React.useMemo((function () {
          var start = (lines.length - options.height | 0) - verticalOffset | 0;
          var offset = start > 0 ? start : 0;
          return Belt_Array.slice(lines, offset, options.height);
        }), [
        lines,
        options.height,
        verticalOffset
      ]);
  var viewport = function (direction) {
    switch (direction) {
      case "Up" :
          var start = lines.length - options.height | 0;
          var limit = Math.max(0, start);
          return setVerticalOffset(function (prev) {
                      return Math.min(prev + 1 | 0, limit);
                    });
      case "Down" :
          return setVerticalOffset(function (prev) {
                      return Math.max(prev - 1 | 0, 0);
                    });
      case "Reset" :
          return setVerticalOffset(function (param) {
                      return 0;
                    });
      
    }
  };
  var screen = function (command) {
    if (typeof command !== "object") {
      return setLines(function (param) {
                  return [];
                });
    }
    var line = command._0;
    setLines(function (lines) {
          return Belt_Array.concatMany([
                      lines,
                      [line]
                    ]);
        });
  };
  return {
          display: display,
          screen: screen,
          viewport: viewport
        };
}

export {
  useDisplay ,
}
/* react Not a pure module */
