// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Web from "./Web.res.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function normalize(classes) {
  return classes.split(" ");
}

function fromObject(obj) {
  return Belt_Array.reduce(Belt_Array.map(Js_dict.entries(obj), (function (param) {
                    if (param[1]) {
                      return param[0];
                    } else {
                      return "";
                    }
                  })), "", (function (classes, $$class) {
                return classes + " " + $$class;
              }));
}

var Cn = {
  normalize: normalize,
  fromObject: fromObject
};

function make(tag) {
  return document.createElement(tag);
}

function makeFromString(tag) {
  return document.createTextNode(tag);
}

function string(text) {
  return document.createTextNode(text);
}

function fromNode(node) {
  return node;
}

function toNode(t) {
  return t;
}

function append(node, nodes) {
  Belt_Array.forEach(nodes, (function (other) {
          node.appendChild(other);
        }));
}

function appendList(t, _nodes) {
  while(true) {
    var nodes = _nodes;
    if (!nodes) {
      return ;
    }
    t.appendChild(nodes.hd);
    _nodes = nodes.tl;
    continue ;
  };
}

function appendTo(node, other) {
  other.appendChild(node);
}

function replaceWith(node, other) {
  node.parentNode.replaceChild(other, node);
}

function remove(node) {
  node.parentNode.removeChild(node);
}

function setText(node, text) {
  node.textContent = text;
}

function getText(node) {
  return node.textContent;
}

function setAttribute(node, name, value) {
  node.setAttribute(name, value);
}

function addClass(node, classes) {
  var classes$1 = classes.split(" ");
  Caml_splice_call.spliceObjApply(node.classList, "add", [classes$1]);
}

function removeClass(node, classes) {
  var classes$1 = classes.split(" ");
  Caml_splice_call.spliceObjApply(node.classList, "remove", [classes$1]);
}

function toggleClass(node, classes, value) {
  var classes$1 = classes.split(" ");
  Belt_Array.forEach(classes$1, (function ($$class) {
          node.classList.toggle($$class, value);
        }));
}

function toggleClasses(t, classes) {
  var entries = Js_dict.entries(classes);
  Belt_Array.forEach(entries, (function (param) {
          toggleClass(t, param[0], param[1]);
        }));
}

function show(node) {
  var style = node.style;
  style.display = "initial";
}

function hide(node) {
  var style = node.style;
  style.display = "none";
}

function onClick(node, handler, options) {
  var options$1 = Belt_Option.getWithDefault(options, {
        once: false
      });
  Web.$$Event.addClickListener(node, handler, options$1);
}

function strings(strings$1) {
  var text = Belt_Array.joinWith(strings$1, " ", (function (x) {
          return x;
        }));
  return document.createTextNode(text);
}

function ref(ref$1, element) {
  ref$1.contents = element;
  return element;
}

function tree(tag, children, ref, $$class, classes, dependencies, attributes) {
  var element = document.createElement(tag);
  append(element, children);
  Belt_Option.map(ref, (function (ref) {
          ref.contents = element;
        }));
  Belt_Option.map($$class, (function ($$class) {
          addClass(element, $$class);
        }));
  Belt_Option.map(classes, (function (classes) {
          toggleClasses(element, classes);
        }));
  Belt_Option.map(dependencies, (function (dependencies) {
          Belt_Array.forEach(dependencies, (function (dependency) {
                  dependency();
                }));
        }));
  Belt_Option.map(attributes, (function (attributes) {
          Belt_Array.forEach(attributes, (function (param) {
                  setAttribute(element, param[0], param[1]);
                }));
        }));
  return element;
}

function $$null() {
  return document.createTextNode("");
}

function space() {
  return document.createTextNode(" ");
}

function newline() {
  return document.createElement("br");
}

var placeholder = (new Proxy({}, {
    get(target, prop) {
      throw new Error("Placeholder access is not allowed! Assign ref first.")
    }
  }));

var Dom = {
  $$null: $$null,
  space: space,
  newline: newline,
  placeholder: placeholder
};

export {
  Cn ,
  make ,
  makeFromString ,
  string ,
  fromNode ,
  toNode ,
  append ,
  appendList ,
  appendTo ,
  replaceWith ,
  remove ,
  setText ,
  getText ,
  setAttribute ,
  addClass ,
  removeClass ,
  toggleClass ,
  toggleClasses ,
  show ,
  hide ,
  onClick ,
  strings ,
  ref ,
  tree ,
  Dom ,
}
/* placeholder Not a pure module */
