// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "./Jq.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var toArray = (function(element) {
  return Array.isArray(element) ? element : [element]
});

function jsx(component, props) {
  return component(props);
}

function jsxKeyed(component, props, key, unit) {
  return component(props);
}

function string(text) {
  return Jq.string(text);
}

function $$int(number) {
  var text = String(number);
  return Jq.string(text);
}

function $$float(number) {
  var text = String(number);
  return Jq.string(text);
}

function jsx$1(string, props) {
  var element = Jq.makeFromString(string);
  Belt_Option.map(props.ref, (function (ref) {
          ref.contents = element;
        }));
  Belt_Option.map(props.class, (function ($$class) {
          Jq.addClass(element, $$class);
        }));
  Belt_Option.map(props.children, (function (child) {
          Jq.append(element, toArray(child));
        }));
  return element;
}

function jsxKeyed$1(string, props, key, unit) {
  return jsx$1(string, props);
}

var Elements = {
  jsx: jsx$1,
  jsxKeyed: jsxKeyed$1,
  jsxs: jsx$1,
  jsxsKeyed: jsxKeyed$1
};

export {
  toArray ,
  jsx ,
  jsxKeyed ,
  string ,
  $$int ,
  $$float ,
  Elements ,
}
/* Jq Not a pure module */
