// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "./Jq.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var toArray = (function(element) {
  return Array.isArray(element) ? element : [element];
});

function jsx(component, props) {
  return component(props);
}

function jsxKeyed(component, props, key, unit) {
  return component(props);
}

function string(text) {
  return Jq.string(text);
}

function $$int(number) {
  var text = String(number);
  return Jq.string(text);
}

function $$float(number) {
  var text = String(number);
  return Jq.string(text);
}

function jsxFragment(props) {
  return Belt_Option.getWithDefault(props.children, Jq.Dom.$$null());
}

function make(tag, props) {
  var element = Jq.make(tag);
  var children = Belt_Option.mapWithDefault(props.children, [], toArray);
  Jq.append(element, children);
  Belt_Option.map(props.bind, (function (ref) {
          ref.contents = element;
        }));
  Belt_Option.map(props.class, (function ($$class) {
          Jq.addClass(element, $$class);
        }));
  Belt_Option.map(props.classes, (function (classes) {
          Jq.toggleClasses(element, classes);
        }));
  Belt_Option.map(props.dependencies, (function (dependencies) {
          Belt_Array.forEach(dependencies, (function (dependency) {
                  dependency();
                }));
        }));
  Belt_Option.map(props.attributes, (function (attributes) {
          Belt_Array.forEach(attributes, (function (param) {
                  Jq.setAttribute(element, param[0], param[1]);
                }));
        }));
  Belt_Option.map(props.onClickOnce, (function (onClick) {
          return Jq.onClick(element, onClick, {
                      once: true
                    });
        }));
  return element;
}

var Make = {
  make: make
};

function jsx$1(string, props) {
  return make(string, props);
}

function jsxKeyed$1(string, props, key, unit) {
  return make(string, props);
}

function someElement(element) {
  return Caml_option.some(element);
}

var Elements = {
  jsx: jsx$1,
  jsxKeyed: jsxKeyed$1,
  jsxs: jsx$1,
  jsxsKeyed: jsxKeyed$1,
  someElement: someElement
};

var jsxs = jsx;

var jsxsKeyed = jsxKeyed;

var text = Jq.strings;

export {
  toArray ,
  jsx ,
  jsxKeyed ,
  jsxs ,
  jsxsKeyed ,
  string ,
  $$int ,
  $$float ,
  jsxFragment ,
  text ,
  Make ,
  Elements ,
}
/* Jq Not a pure module */
