// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "./Jq.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var $$null = Jq.Dom.$$null;

function $$float(number) {
  return Jq.string(String(number));
}

function $$int(number) {
  return Jq.string(String(number));
}

function jsx(string, props) {
  var element = Jq.makeFromString(string);
  Belt_Option.map(props.class, (function ($$class) {
          Jq.addClass(element, $$class);
        }));
  Belt_Option.map(props.children, (function (child) {
          Jq.append(element, [child]);
        }));
  return element;
}

function jsxKeyed(string, props, key, unit) {
  return jsx(string, props);
}

var Elements = {
  jsx: jsx,
  jsxKeyed: jsxKeyed,
  jsxs: jsx,
  jsxsKeyed: jsxKeyed
};

var string = Jq.string;

export {
  $$null ,
  $$float ,
  $$int ,
  string ,
  Elements ,
}
/* Jq Not a pure module */
