// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jqx from "./Jqx.res.mjs";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function jsx(component, props) {
  return component(props);
}

function jsxKeyed(component, props, key, unit) {
  return component(props);
}

function jsxFragment(props) {
  return Belt_Option.getWithDefault(props.children, Jqx.$$null());
}

function jsx$1(string, props) {
  return Jqx.make(string, props);
}

function jsxKeyed$1(string, props, key, unit) {
  return Jqx.make(string, props);
}

function someElement(element) {
  return element;
}

var Elements = {
  jsx: jsx$1,
  jsxKeyed: jsxKeyed$1,
  jsxs: jsx$1,
  jsxsKeyed: jsxKeyed$1,
  someElement: someElement
};

var jsxs = jsx;

var jsxsKeyed = jsxKeyed;

var array = Jqx.array;

var string = Jqx.string;

var $$int = Jqx.$$int;

var $$float = Jqx.$$float;

export {
  jsx ,
  jsxKeyed ,
  jsxs ,
  jsxsKeyed ,
  array ,
  string ,
  $$int ,
  $$float ,
  jsxFragment ,
  Elements ,
}
/* Jqx Not a pure module */
