// Generated by ReScript, PLEASE EDIT WITH CARE


function Make(Info) {
  var states = function (pairs) {
    return Object.fromEntries(pairs);
  };
  return {
          states: states
        };
}

export {
  Make ,
}
/* No side effect */
