// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Node = {};

function addClickListener(node, handler, options) {
  node.addEventListener("click", handler, options);
}

var $$Event = {
  addClickListener: addClickListener
};

var Style = {};

var ClassList = {};

var $$Document = {};

export {
  $$Node ,
  $$Event ,
  Style ,
  ClassList ,
  $$Document ,
}
/* No side effect */
