// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Node = {};

function addClickListener(node, handler, options) {
  node.addEventListener("click", handler, options);
  return handler;
}

function removeClickListener(node, handler) {
  node.removeEventListener("click", handler);
}

var $$Event = {
  addClickListener: addClickListener,
  removeClickListener: removeClickListener
};

var Style = {};

var ClassList = {};

var $$Document = {};

export {
  $$Node ,
  $$Event ,
  Style ,
  ClassList ,
  $$Document ,
}
/* No side effect */
