// Generated by ReScript, PLEASE EDIT WITH CARE


var screens = [
  {
    place: "Center",
    computer: "Watch",
    options: [[
        "Вернуться",
        "Center"
      ]]
  },
  {
    place: "Table",
    computer: "Watch",
    options: [[
        "Вернуться",
        "Center"
      ]]
  },
  {
    place: "Window",
    computer: "Watch",
    options: [[
        "Вернуться",
        "Center"
      ]]
  },
  {
    place: "Door",
    computer: "Door",
    options: [[
        "Вернуться",
        "Center"
      ]]
  }
];

export {
  screens ,
}
/* No side effect */
