// Generated by ReScript, PLEASE EDIT WITH CARE


var screens = [
  {
    place: "Table",
    computer: "Watch",
    description: "Вы стоите у стола. На столе в беспорядке лежат заметки, ручки, бумажки и прочие предметы.",
    options: [[
        "Вернуться",
        "Room"
      ]]
  },
  {
    place: "Window",
    computer: "Watch",
    description: "Вы стоите у окна. За окном - улица, на которой виднеются машины и люди.",
    options: [[
        "Вернуться",
        "Room"
      ]]
  },
  {
    place: "Door",
    computer: "Door",
    description: "Вы стоите у двери. На двери надпись: \"Выход\", а также электронный код-замок. Дверь заперта.",
    options: [[
        "Вернуться",
        "Room"
      ]]
  }
];

export {
  screens ,
}
/* No side effect */
