// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "../rooms/Link.res.mjs";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function useSwitch(initial) {
  var match = React.useState(function () {
        return initial;
      });
  var setState = match[1];
  var state = match[0];
  var toggle = function (state) {
    setState(function (param) {
          return state;
        });
  };
  var content = function (children) {
    if (state === "Visited") {
      return children;
    } else {
      return null;
    }
  };
  return {
          state: state,
          content: content,
          toggle: toggle
        };
}

var Base = {
  useSwitch: useSwitch
};

function useSwitch$1(initialOpt, onToggleOpt) {
  var initial = initialOpt !== undefined ? initialOpt : "Unvisited";
  var onToggle = onToggleOpt !== undefined ? onToggleOpt : (function () {
        
      });
  var match = useSwitch(initial);
  var toggle = match.toggle;
  var state = match.state;
  var onClick = function () {
    onToggle();
    toggle("Visited");
  };
  var link = function (children) {
    if (state === "Unvisited") {
      return JsxRuntime.jsx(Link.make, {
                  onClick: onClick,
                  children: children
                });
    } else {
      return children;
    }
  };
  return {
          link: link,
          content: match.content
        };
}

var Toggle = {
  useSwitch: useSwitch$1
};

export {
  Base ,
  Toggle ,
}
/* Link Not a pure module */
