// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: "Hello!",
              className: "w-full h-full min-h-screen m-0 p-2 bg-gray-900 text-gray-100"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
