// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Game(props) {
  return JsxRuntime.jsx("div", {
              children: "Hello!"
            });
}

var make = Game;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
