// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "./lib/Jq.res.mjs";
import * as Content from "./game/data/Content.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Error from "@rescript/core/src/Core__Error.res.mjs";

function render(children) {
  return Jq.Tree.build(Jq.makeClass("div", "w-full h-full min-h-screen m-0 p-6 bg-gray-900 text-gray-100"), [{
                TAG: "And",
                _0: Jq.makeClass("div", "mx-auto min-w-xl max-w-5xl"),
                _1: [{
                    TAG: "Last",
                    _0: children
                  }]
              }]);
}

var App = {
  render: render
};

function mount(root, children) {
  var root$1 = Jq.fromNode(root);
  Jq.append(root$1, [children]);
}

var rootElement = document.querySelector("#root");

if (rootElement !== undefined) {
  mount(Caml_option.valFromOption(rootElement), render(Content.RoomD.render()));
} else {
  Core__Error.panic("No root element found!");
}

export {
  App ,
  mount ,
}
/* rootElement Not a pure module */
