// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./Game.res.mjs";
import * as Core__Error from "@rescript/core/src/Core__Error.res.mjs";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

function Main$App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("article", {
                    children: props.children,
                    className: "prose prose-slate dark:prose-invert"
                  }),
              className: "w-full h-full min-h-screen m-0 p-2 bg-gray-900 text-gray-100"
            });
}

var App = {
  make: Main$App
};

var rootElement = document.querySelector("#root");

if (rootElement == null) {
  Core__Error.panic("No root element found!");
} else {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(Main$App, {
            children: JsxRuntime.jsx(Game.make, {})
          }));
}

export {
  App ,
}
/* rootElement Not a pure module */
