// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jq from "./lib/Jq.res.mjs";
import * as Content from "./game/data/Content.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Error from "@rescript/core/src/Core__Error.res.mjs";

function render(children) {
  return Jq.append(Jq.addClass(Jq.make("div"), "w-full h-full min-h-screen m-0 p-6 bg-gray-900 text-gray-100"), [Jq.append(Jq.addClass(Jq.make("div"), "mx-auto min-w-xl max-w-5xl"), [children])]);
}

var App = {
  render: render
};

function mount(root, children) {
  Jq.append(Jq.fromNode(root), [children]);
}

var rootElement = document.querySelector("#root");

if (rootElement !== undefined) {
  mount(Caml_option.valFromOption(rootElement), render(Content.RoomD.render()));
} else {
  Core__Error.panic("No root element found!");
}

export {
  App ,
  mount ,
}
/* rootElement Not a pure module */
