// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Story$Text(props) {
  return JsxRuntime.jsx("article", {
              children: props.children,
              className: "prose prose-slate dark:prose-invert"
            });
}

var $$Text = {
  make: Story$Text
};

export {
  $$Text ,
}
/* react/jsx-runtime Not a pure module */
